application: sp13-twilio
version: 30
runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /stylesheets
  static_dir: stylesheets

- url: .*
  script: main.app

libraries:
- name: webapp2
  version: "2.5.2"
  
- name: jinja2
  version: latest

inbound_services:
- channel_presence



